name: Build Docker Actions
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in projetos directory
        run: ls -R helloworld

      - name: Build the Docker image
        run: docker build -f helloworld/Dockerfile -t marinamagaldib/fastapi-app:${{ github.sha }} helloworld/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push marinamagaldib/fastapi-app:${{ github.sha }}
