name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build -f Dockerfile -t marinamagaldib/fastapi-app:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push marinamagaldib/fastapi-app:${{ github.sha }}

      - name: Checkout gitops repo
        uses: actions/checkout@v3
        with:
          repository: marinamagaldi/gitops
          token: ${{ secrets.ACCESS_TOKEN_OPS }}
          path: mychart

      - name: Atualizar tag no values.yaml
        run: |
          cd mychart  # Caminho onde o Helm chart está localizado dentro do repositório gitops
          sed -i 's|image:.*|image: marinamagaldib/fastapi-app:${{ github.sha }}|' values.yaml

      - name: Verificar valores.yaml
        run: |
          cd mychart
          cat values.yaml

      - name: Commit e Push das alterações para gitops
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add mychart/values.yaml
          git commit -m "update docker tag para: ${{ github.sha }}"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN_OPS }}@github.com/marinamagaldi/gitops.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_OPS }}
